[package]
name = "auto_usb_backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
fs_extra = "1.2.0"
serde = { version = "1.0.139", features = ["derive"] }
toml = "0.5.9"
